//
//  main.cpp
//  2
//
//  Created by Belden on 10/21/13.
//  Copyright (c) 2013 bpb. All rights reserved.
//

/*
 
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 
 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 
 Answer: 
 4613732
 
 */

#include <iostream>

int main(int argc, const char * argv[])
{
    long preFib=0, temp=0;
    long fib = 1;
    long sum = 0;
    
    while (fib < 4000000)
    {
        temp = fib;
        fib = fib + preFib;
        preFib=temp;
        
        if (fib%2 == 0)
            sum+=fib;
    
    }

    std::cout << sum << std::endl;
    
    return 0;
}

