//
//  main.cpp
//  12
//
//  Created by Belden on 10/21/13.
//  Copyright (c) 2013 bpb. All rights reserved.
//

/*
 
 The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 
 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 
 Let us list the factors of the first seven triangle numbers:
 
 1: 1
 3: 1,3
 6: 1,2,3,6
 10: 1,2,5,10
 15: 1,3,5,15
 21: 1,3,7,21
 28: 1,2,4,7,14,28
 We can see that 28 is the first triangle number to have over five divisors.
 
 What is the value of the first triangle number to have over five hundred divisors?
 
 Answer: 76576500
 
 */

#include <iostream>

int main(int argc, const char * argv[])
{
    // get a triangle number
    long sum = 0;
    const long MAX = 999999999999;
    
    
    for (long i = 1; i<MAX; i++)
    {
        int count = 0;
        sum += i;
        //std::cout << "sum is: " << sum << std::endl;
        //std::cout << "factors are: " << std::endl;
        if (sum > 75000000)
        {
            for (long j = 1; j<=sum; j++)
            {
                if (sum%j == 0)
                {
                    //std::cout << j << std::endl;
                    count++;
                    //std::cout << "count is: " << count << std::endl;
                }
                if (count > 500)
                    goto finish;
            }
        }
    }
    
finish:
    std::cout << sum << std::endl;
    
    return 0;
}

